FROM node:18-slim
WORKDIR /app

ARG NPM_TOKEN_ARG
ENV NPM_TOKEN ${NPM_TOKEN_ARG}

COPY .npmrc package.json package-lock.json .
RUN npm ci

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/index.js"]
