FROM node:18-slim as base

WORKDIR /app

FROM base as builder

COPY package.json package-lock.json .

RUN --mount=type=secret,id=npmrc,target=/app/.npmrc npm ci

COPY . .

RUN npm run build # outputs a dist/

FROM base as production
COPY --from=builder /app/dist .

CMD ["node", "dist/index.js"]
